### PR TITLE
Convert shortcuts into one menu using batch script

### PR DESCRIPTION
**Pull request by ODAKAB**
image

### CODE REVIEW

**Review by jojo2357 — CHANGES_REQUESTED** [review]
Im really thankful that you put in the time to make this. However, I think the shortcuts should stay but rather a batch script should edit/create shortcuts so that the user can move those one-click shortcuts to their desktop, for example. This is what i thought you meant by your comments in #26. I understand it may take some time but im sure it can be done.

**Comment by ODAKAB** [comment]
Sorry, I can't understand your concern, user can still create a shortcut of this script and place it anywhere. Why don't you think this as main launcher of your app?

**Comment by jojo2357** [comment]
I suppose but the idea I have in mind is that it should come out-of-the-box-one-click-to-run. If you could make a batch file or an option in the menu to create these shortcuts as to convenience the user, that would be absolutely perfect.

**Comment by ODAKAB** [comment]
If It's possible to generate shortcuts, I will try. Do you want it as an extra or default?
If you want it as an extra, It can be option 10 that generates all options as shortcuts in Shortcuts folder.
Or like 9 new options that generates shortcut for specified option.
I can also seperate ShortcutGenerator

**Comment by jojo2357** [comment]
I think having a shortcut generator bat plus an option in the menu that calls it would be the best option here so the user could hypothetically two clicks to run.

**Comment by ODAKAB** [comment]
Reminding that option 10 doesn't need to call another batch script, as i can directly code it into script too.
Calling would be for having a standalone ShortcutGenerator file.

**Comment by jojo2357** [comment]
Im aware. I was just hoping that the user could have a single click to fix the shortcuts with the option to do it in the menu as well. The launcher could go in the root directory as well and leave the shortcuts in their folder.

**Comment by ODAKAB** [comment]
Generated shortcuts aren't set to run as administrator, couldn't find how to do it.
https://www.vbsedit.com/html/e6ac108b-15f6-4a54-891f-589e8b687ace.asp

**Comment by jojo2357** [comment]
Okay and my other concern is that running the linkers, finders, and unlinkers all require admin perms so would there be a way to gain admin perms when the user selects it? also making the shortcuts using admin perms is a **must**. 

A possible option for solving admin issue for shortcuts:
https://superuser.com/questions/1440665/create-windows-shortcut-with-run-as-administrator-option-enabled

**Comment by ODAKAB** [comment]
MusicDRP script already requests for admin permissions on start, and that passes to called scripts.
I checked the topic you sent, actually I tried to use HxD on .lnk but It just gave me where it pointed to. Seems like they also thought a workaround like me and editing file in hex.
I liked this solution but I'm a bit busy today and tomorrow. Feel free to merge and finish setting run as admin on shortcuts if you want, because I will start working back a bit late.

**Comment by jojo2357** [comment]
I made some changes please review most recent commit

**Comment by jojo2357** [comment]
Im going to merge and if you would like to make changes after, feel free to open a new pr.

**Review by jojo2357 — APPROVED** [review]

**Comment by RoguedBear** [comment]
I tested the `Music_DRP_Launcher.bat`, when I selected the `0` option the shortcuts folder was not created, but when I selected 2nd option _Launch DRP_, The `shortcuts/` folder was generated also opening the `GroovyRP.exe`

**Comment by jojo2357** [comment]
Hmmm the create option is supposed to run mdrp actually since the shortcut creation is in the exe. Ill look into it thanks

**Comment by RoguedBear** [comment]
Also noticed one more thing. Link/Unlink options [4 to 7] error out with `'D:\Portable' is not recognized as an internal or external command,
operable program or batch file.` when there are spaces in the repository path just like how it happend in #16

**Comment by jojo2357** [comment]
not this again...

**Pull request merged**
